// This class handles the devices connecting to the internal MQTT broker. This includes both device provisioning
// and minimal wrappers for actual data exchange. The device class is responsible for generating/parsing the payload.

import { generateDeployResponse } from './provisioning'
import { TypedEmitter } from 'tiny-typed-emitter'
import { Client, PublishPacket, type Broker } from '../mqtt-broker'
import { ClipDeployMessage, ClipMessage } from './clip'

import log from '@/util/logging'
import { Metadata } from '../thinq'

type DeviceEvents = {
    // Emitted before any model-specific decoder sees the packet. Monitoring and
    // capture use this event so an unsupported/throwing decoder cannot hide wire data.
    rawData: (packet: Buffer) => void
    packetData: (packet: Buffer, mapped: boolean) => void
    data: (packet: Buffer) => void
    sendData: (buf: Buffer) => void
    close: () => void
}

export class Device extends TypedEmitter<DeviceEvents> {
    // this could be a stream but why bother...
    readonly platform = 'thinq2'
    private currentPacketMapped = false

    constructor(
        readonly broker: Broker,
        readonly topic: string,
        readonly id: string,
        readonly meta: Metadata,
    ) {
        super()
    }

    send(cmd: string, type: number, data: string | object) {
        const messagestr = JSON.stringify({ did: this.id, mid: Date.now(), cmd: cmd, type: type, data: data })
        this.broker.publish(
            { topic: this.topic, retain: false, qos: 0, dup: false, payload: messagestr },
            null /* message generated by the broker itself */,
        )
    }

    send_packet(buf: Buffer) {
        this.emit('sendData', buf)
        this.send('packet', 1, buf.toString('hex'))
    }

    markCurrentPacketMapped() {
        this.currentPacketMapped = true
    }

    receivePacket(buf: Buffer) {
        this.currentPacketMapped = false
        this.emit('rawData', buf)
        try {
            this.emit('data', buf)
        } finally {
            this.emit('packetData', buf, this.currentPacketMapped)
        }
    }
}

function trimNull(buf: Buffer) {
    if (!buf || !buf.length || buf[buf.length - 1]) return buf
    return buf.subarray(0, buf.length - 1)
}

type ClientWithExtra = Client & {
    deviceObj: undefined | Device
    deployMsg: undefined | ClipDeployMessage
    pacTimeSyncRetried?: boolean
    pacTimeSyncTimeouts?: Array<ReturnType<typeof setTimeout>>
    pacTimeSyncInterval?: ReturnType<typeof setInterval>
}

const PAC_TIME_SYNC_RETRY_DELAYS_MS = [5_000, 15_000, 30_000] as const
const PAC_TIME_SYNC_INTERVAL_MS = 60_000

type DeviceAcceptorEvents = {
    newDevice: (dev: Device) => void
    dropDevice: (id: string) => void
}

export function timeSyncPayload(now: Date, _timezone: string | undefined) {
    // ThinQ's wire format is UTC and uses JavaScript's zero-based month.
    // Converting it to appliance-local time or a one-based month makes PAC
    // reject the response after a full controller reboot.
    return Buffer.from([
        now.getUTCFullYear() % 100,
        now.getUTCMonth(),
        now.getUTCDate(),
        now.getUTCHours(),
        now.getUTCMinutes(),
        now.getUTCSeconds(),
        now.getUTCDay(),
    ])
}

export class DeviceAcceptor extends TypedEmitter<DeviceAcceptorEvents> {
    clientsById: Record<string, Client> = {}
    constructor(readonly broker: Broker) {
        super()

        broker.on('publish', (packet, client) => {
            if (client) {
                log('incoming', packet.topic, packet.payload.toString('utf-8'), 'retain:', packet.retain)
            } else {
                log('outgoing', packet.topic, packet.payload.toString('utf-8'), 'retain:', packet.retain)
                return // don't process outgoing packets further
            }

            try {
                if (packet.topic.indexOf('clip/') >= 0) {
                    const payload = JSON.parse(trimNull(Buffer.from(packet.payload)).toString('utf-8'))
                    this.mqtt(packet.topic, payload, client as ClientWithExtra)
                }
            } catch (err) {
                console.warn(err, packet.payload.toString('hex'))
            }
        })

        broker.on('disconnect', this.disconnected.bind(this))
    }

    mqtt(topic: string, payload: ClipMessage, client: ClientWithExtra) {
        // experiment: try to support devices which use other topic formats
        topic = topic.replace(/^.*\/clip/, 'clip')

        if (topic === 'clip/message/devices/' + payload.did) {
            if (payload.cmd === 'completeProvisioning_ack') {
                this.completeProvisioning(payload.did, payload, client)
            }

            if (payload.cmd === 'device_packet' && payload.did === client.deployMsg?.did) {
                if (client.deviceObj) {
                    const buf = Buffer.from(payload.data as string, 'hex')
                    client.deviceObj.receivePacket(buf)

                    // PAC can ignore the response sent immediately after
                    // provisioning while its display controller is still
                    // starting. Retry once after the first appliance packet,
                    // when the device is demonstrably ready to receive it.
                    if (client.deployMsg?.kind === 'PAC_910604_WW' && !client.pacTimeSyncRetried) {
                        client.pacTimeSyncRetried = true
                        this.timeSyncRequest(client, 'first PAC packet')
                    }
                }
            }

            if (payload.cmd === 'req_timesync' && client.deployMsg && payload.did === client.deployMsg.did) {
                this.timeSyncRequest(client, 'device request')
            }
        }

        if (topic === 'clip/provisioning/devices/' + payload.did) {
            if (payload.cmd === 'preDeploy' || payload.cmd === 'deploy') {
                client.deployMsg = payload as ClipDeployMessage
                this.broker.publish(
                    {
                        topic: 'lime/devices/' + payload.did,
                        retain: false,
                        qos: 0,
                        dup: false,
                        payload: JSON.stringify(generateDeployResponse(payload as ClipDeployMessage)),
                    },
                    null,
                )
            }
        }
    }

    completeProvisioning(deviceId: string, payload: ClipMessage, client: ClientWithExtra) {
        if (!client.deployMsg) {
            console.warn('completeProvisioning_ack received without deploy/preDeploy')
            return
        }

        if (client.deviceObj) {
            console.warn('completeProvisioning_ack received twice?')
            return
        }

        if (this.clientsById[deviceId]) {
            console.warn(`device ${deviceId} already connected, dropping the old one`)
            this.clientsById[deviceId].destroy()
        }

        this.clientsById[deviceId] = client

        const meta: Metadata = {
            modelId: client.deployMsg.kind,
            modelName: client.deployMsg.data?.appInfo?.modelName,
            swVersion: client.deployMsg.data?.appInfo?.softVer,
            deviceType: client.deployMsg.data?.appInfo?.DeviceType,
        }

        const dev = new Device(this.broker, 'lime/devices/' + deviceId, deviceId, meta)
        client.deviceObj = dev
        this.emit('newDevice', dev)

        // PAC_910604_WW does not always request time synchronization itself.
        // Without an initial response its standby clock remains on the Wi-Fi
        // connection prompt even though MQTT provisioning has completed.
        if (meta.modelId === 'PAC_910604_WW') {
            this.timeSyncRequest(client, 'provisioning')
            this.schedulePacTimeSync(client)
        }
    }

    schedulePacTimeSync(client: ClientWithExtra) {
        this.clearPacTimeSyncSchedule(client)

        const syncIfConnected = () => {
            const deviceId = client.deployMsg?.did
            if (!deviceId || !client.deviceObj || this.clientsById[deviceId] !== client) return
            this.timeSyncRequest(client, 'scheduled retry')
        }

        client.pacTimeSyncTimeouts = PAC_TIME_SYNC_RETRY_DELAYS_MS.map((delay) => {
            const timeout = setTimeout(syncIfConnected, delay)
            timeout.unref?.()
            return timeout
        })
        client.pacTimeSyncInterval = setInterval(syncIfConnected, PAC_TIME_SYNC_INTERVAL_MS)
        client.pacTimeSyncInterval.unref?.()
    }

    clearPacTimeSyncSchedule(client: ClientWithExtra) {
        for (const timeout of client.pacTimeSyncTimeouts ?? []) clearTimeout(timeout)
        client.pacTimeSyncTimeouts = undefined
        if (client.pacTimeSyncInterval) clearInterval(client.pacTimeSyncInterval)
        client.pacTimeSyncInterval = undefined
    }

    timeSyncRequest(client: ClientWithExtra, reason = 'unspecified') {
        const buf = timeSyncPayload(new Date(), client.deployMsg?.data?.appInfo?.timezone)

        const deviceId = client.deployMsg?.did
        if (!deviceId) return

        log('status', deviceId, 'time sync response', reason, buf.toString('hex'))

        this.broker.publish(
            {
                topic: 'lime/devices/' + deviceId,
                retain: false,
                qos: 0,
                dup: false,
                payload: JSON.stringify({
                    did: deviceId,
                    mid: Date.now(),
                    cmd: 'resp_timesync',
                    type: 1,
                    data: buf.toString('base64'),
                }),
            },
            null,
        )
    }

    disconnected(_client: Client) {
        let client = _client as ClientWithExtra
        this.clearPacTimeSyncSchedule(client)
        if (client.deviceObj) {
            delete this.clientsById[client.deviceObj.id]
            this.emit('dropDevice', client.deviceObj.id)
            client.deviceObj.emit('close')
            client.deviceObj = undefined
        }
    }
}
